export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SET_MESSAGE="SET_MESSAGE";
export const CLEAR_MESSAGE="CLEAR_MESSAGE";
export const LOGOUT="LOGOUT";
export const GETARTICLE_SUCCESS="GETARTICLE_SUCCESS";
export const SEARCH_ARTICLE="SEARCH_ARTICLE";
export const ONE_ARTICLE="ONE_ARTICLE";